import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { RagConversation } from './rag'
import { downloadDir, join } from '@tauri-apps/api/path'
import { writeFile } from '@tauri-apps/plugin-fs'

const { getConversationMock, generatePdfMock } = vi.hoisted(() => ({
  getConversationMock: vi.fn(),
  generatePdfMock: vi.fn(),
}))

vi.mock('./rag', () => ({ ragGetConversation: getConversationMock }))
vi.mock('./ocr-pdf', () => ({ generateNativeOcrPdfBytes: generatePdfMock }))
vi.mock('@tauri-apps/api/path', () => ({
  downloadDir: vi.fn(),
  join: vi.fn(),
}))
vi.mock('@tauri-apps/plugin-fs', () => ({ writeFile: vi.fn() }))

const conversation: RagConversation = {
  id: 'conv-42',
  title: 'Acta <sindical>',
  messages: [
    { id: 'm1', role: 'user', content: 'Pregunta\ncon dos líneas', sources: [], createdAt: 1 },
    { id: 'm2', role: 'assistant', content: '**Respuesta** con `formato`', sources: [], createdAt: 2 },
  ],
}

beforeEach(() => {
  vi.resetModules()
  vi.mocked(getConversationMock).mockReset()
  vi.mocked(generatePdfMock).mockReset()
  vi.mocked(downloadDir).mockReset()
  vi.mocked(join).mockReset()
  vi.mocked(writeFile).mockReset()
})

describe('buildRagConversationPdfHtml', () => {
  it('escapes title and questions, renders answers, and preserves message order', async () => {
    const { buildRagConversationPdfHtml } = await import('./rag-chat-export')
    const html = buildRagConversationPdfHtml(conversation)

    expect(html).toContain('<h1>Acta &lt;sindical&gt;</h1>')
    expect(html).toContain('Pregunta<br>con dos líneas')
    expect(html).toContain('<strong>Respuesta</strong>')
    expect(html).toContain('<code>formato</code>')
    expect(html.indexOf('Pregunta')).toBeLessThan(html.indexOf('Respuesta'))
    expect(html).not.toContain('<sindical>')
  })
})

describe('downloadRagConversationPdf', () => {
  it('loads the requested id and writes generated bytes to Downloads', async () => {
    const bytes = Uint8Array.from([1, 2, 3])
    getConversationMock.mockResolvedValue(conversation)
    generatePdfMock.mockResolvedValue(bytes)
    vi.mocked(downloadDir).mockResolvedValue('C:/Users/test/Downloads')
    vi.mocked(join).mockResolvedValue('C:/Users/test/Downloads/Acta sindical - conv-42.pdf')
    vi.mocked(writeFile).mockResolvedValue(undefined)

    const { downloadRagConversationPdf } = await import('./rag-chat-export')
    await expect(downloadRagConversationPdf('conv-42')).resolves.toBe(
      'C:/Users/test/Downloads/Acta sindical - conv-42.pdf'
    )

    expect(getConversationMock).toHaveBeenCalledWith('conv-42')
    expect(generatePdfMock).toHaveBeenCalledWith(expect.stringContaining('Acta &lt;sindical&gt;'))
    expect(join).toHaveBeenCalledWith(
      'C:/Users/test/Downloads',
      'Acta sindical - conv-42.pdf'
    )
    expect(writeFile).toHaveBeenCalledWith(
      'C:/Users/test/Downloads/Acta sindical - conv-42.pdf',
      bytes
    )
  })

  it('does not write when PDF generation fails', async () => {
    getConversationMock.mockResolvedValue(conversation)
    generatePdfMock.mockRejectedValue(new Error('pdf failed'))

    const { downloadRagConversationPdf } = await import('./rag-chat-export')
    await expect(downloadRagConversationPdf('conv-42')).rejects.toThrow('pdf failed')
    expect(writeFile).not.toHaveBeenCalled()
  })
})
