import { invoke } from '@tauri-apps/api/core'
import { join } from '@tauri-apps/api/path'
import { mkdir, remove, writeFile } from '@tauri-apps/plugin-fs'
import { getStore } from './db'
import { importClassifiedPathsIntoCollection } from './collection-import'
import sample from '../assets/sample-collection/documents.json'

/**
 * The sample collections a new archive opens with (T-37, real material since
 * 2026-10-08): Mar del Plata council minutes of 1891, houses from the UNMDP
 * heritage catalogue and La Capital pages from the 1965 filleting strike. Each
 * document arrives with its text and the analysis already done — entities
 * (places on the map), relations, notes, topics and a summary — so every view
 * has something to show before the user spends anything. Embeddings are left
 * for the user's own batch.
 *
 * `documents.json` and the images are generated by
 * `tablero-producto/herramientas-capturas/muestra-app.py`. The images ship
 * inside the frontend bundle; import needs a file on disk, so each one is
 * written to a staging folder in the data directory (inside the fs scope),
 * imported through the normal path and removed afterwards.
 */

type EntityType = 'person' | 'organization' | 'place' | 'date'

interface SampleDocument {
  file: string
  title: string
  text: string
  metadata: Record<string, string>
  topics: string[]
  entities: [EntityType, string][]
  triples: [string, string, string][]
  notes: string[]
  summary: string
}

interface SampleCollection {
  name: string
  description: string
  documents: SampleDocument[]
}

interface SampleData {
  places: Record<string, [number, number]>
  collections: SampleCollection[]
}

const IMAGE_URLS = import.meta.glob<string>('../assets/sample-collection/*.jpg', {
  query: '?url',
  import: 'default',
  eager: true,
})

/** Every sample collection id starts with this, so sync can recognise them
 *  and keep them on this device: the push skips every row under them
 *  (`sync::push::SAMPLE_COLLECTION_ID_PREFIX`, keep both in step). */
export const SAMPLE_COLLECTION_ID_PREFIX = '00000000-0000-4000-8000-0000005a3e'

const sampleCollectionId = (index: number) =>
  `${SAMPLE_COLLECTION_ID_PREFIX}${String(index + 1).padStart(2, '0')}`

function urlFor(file: string): string {
  const entry = Object.entries(IMAGE_URLS).find(([path]) => path.endsWith(`/${file}`))
  if (!entry) throw new Error(`sample image missing from the bundle: ${file}`)
  return entry[1]
}

function execute(sql: string, params: unknown[]): Promise<unknown> {
  return invoke('db_execute', { sql, params })
}

/** Writes the analysis a document comes with, as if the user had run it. */
async function storeAnalysis(
  doc: SampleDocument,
  itemId: string,
  assetId: string,
  places: SampleData['places']
): Promise<void> {
  const store = getStore()
  const now = Date.now()
  if (doc.text) {
    await store.extractions.upsert({ assetId, textContent: doc.text, method: 'sample' })
  }
  await store.fts.indexItem(itemId, doc.title, JSON.stringify(doc.metadata), doc.text)

  for (const [type, value] of doc.entities) {
    const start = Math.max(doc.text.indexOf(value), 0)
    const geo = type === 'place' ? places[value] : undefined
    await execute(
      `INSERT INTO entities (id, item_id, asset_id, entity_type, value, start_offset, end_offset,
         confidence, source, model_name, created_at, latitude, longitude, geo_status)
       VALUES (?, ?, ?, ?, ?, ?, ?, 1, 'ner', 'ejemplo', ?, ?, ?, ?)`,
      [
        crypto.randomUUID(),
        itemId,
        assetId,
        type,
        value,
        start,
        start + value.length,
        now,
        geo?.[0] ?? null,
        geo?.[1] ?? null,
        type !== 'place' ? 'skipped' : geo ? 'resolved' : 'not_found',
      ]
    )
  }
  for (const [subject, predicate, object] of doc.triples) {
    await execute(
      `INSERT INTO triples (id, item_id, asset_id, subject, predicate, object, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [crypto.randomUUID(), itemId, assetId, subject, predicate, object, now]
    )
  }
  for (const content of doc.notes) await store.notes.create({ itemId, content })
  if (doc.topics.length > 0) await store.topics.addTopicsToItem(itemId, doc.topics)
  if (doc.summary) {
    await execute(
      `INSERT INTO llm_results (id, target_id, target_type, job_type, result, created_at)
       VALUES (?, ?, 'item', 'summarize', ?, ?)`,
      [`llr-item-${itemId}-summarize`, itemId, doc.summary, now]
    )
  }
}

/** Creates the sample collections and returns the first one's id and name. */
export async function loadSampleCollection(): Promise<{ id: string; name: string }> {
  const store = getStore()
  const { places, collections } = sample as unknown as SampleData
  const dataDir = await invoke<string>('resolve_data_dir')
  const staging = await join(dataDir, 'sample-staging')
  await mkdir(staging, { recursive: true })

  const created: { id: string; name: string }[] = []
  try {
    for (const [index, spec] of collections.entries()) {
      const collection = await store.collections.create({
        id: sampleCollectionId(index),
        name: spec.name,
        description: spec.description,
      })
      created.push({ id: collection.id, name: collection.name })
      for (const doc of spec.documents) {
        const bytes = new Uint8Array(await (await fetch(urlFor(doc.file))).arrayBuffer())
        const path = await join(staging, doc.file)
        await writeFile(path, bytes)
        // One file at a time, so each document keeps its own title.
        const result = await importClassifiedPathsIntoCollection([path], collection.id, {
          baseErrorMessage: 'sample import failed',
          overrides: { title: doc.title, allowDuplicate: true, extraMetadata: doc.metadata },
        })
        if (result.importErrors.length > 0) throw new Error(result.importErrors.join('; '))
        const item = result.createdItems[0]
        const asset = item && (await store.assets.findByItem(item.id))[0]
        if (item && asset) await storeAnalysis(doc, item.id, asset.id, places)
      }
    }
  } finally {
    await remove(staging, { recursive: true }).catch(() => {})
  }
  return created[0]!
}
