<script lang="ts">
  /**
   * The single gate every icon in the app passes through.
   *
   * No component imports from '@lucide/svelte' or hand-writes an <svg> — the
   * ESLint rule in eslint.config.js enforces that. Adding an icon means one
   * entry in ACTION_ICON_NAMES and one entry in the map below.
   *
   * See ActionIcon.types.ts for the contract this component implements.
   */
  import {
    Bell,
    Bold,
    BrushCleaning,
    Check,
    CheckCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    CircleCheck,
    CirclePlay,
    CircleQuestionMark,
    CircleX,
    Code,
    Copy,
    Crop,
    Database,
    Download,
    Eraser,
    Expand,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileAudio,
    FileBraces,
    FileImage,
    FileSpreadsheet,
    FileText,
    FileUp,
    Folder,
    FolderPlus,
    Hand,
    Heading1,
    Heading2,
    Heading3,
    Italic,
    Languages,
    Link,
    List,
    ListOrdered,
    LoaderCircle,
    MapPin,
    MapPinPen,
    MessageCircle,
    MessageCirclePlus,
    Mic,
    Moon,
    PanelLeft,
    PanelLeftClose,
    Pause,
    Pencil,
    Play,
    Redo2,
    RefreshCw,
    RotateCcw,
    RotateCw,
    Save,
    Search,
    SearchX,
    Send,
    Settings,
    SkipBack,
    SkipForward,
    Square,
    TextQuote,
    Trash2,
    TriangleAlert,
    Underline,
    Undo2,
    Unlink,
    Volume2,
    Wrench,
    X,
    ZoomIn,
    ZoomOut,
  } from '@lucide/svelte'
  import type { Component } from 'svelte'
  import type { ActionIconName, ActionIconSize } from './ActionIcon.types'
  import RotateFineCcw from './icons/RotateFineCcw.svelte'
  import RotateFineCw from './icons/RotateFineCw.svelte'

  type IconComponent = Component<{ size?: number }>

  /**
   * Name -> glyph. Keyed by ActionIconName, so a name added to the catalogue
   * without an entry here is a compile error rather than a silently blank icon
   * (which is what the previous {#if} chain produced).
   */
  const ICONS: Record<ActionIconName, IconComponent> = {
    bell: Bell,
    bold: Bold,
    broom: BrushCleaning,
    check: Check,
    'check-check': CheckCheck,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'chevrons-left': ChevronsLeft,
    'chevrons-right': ChevronsRight,
    'circle-check': CircleCheck,
    'circle-help': CircleQuestionMark,
    'circle-play': CirclePlay,
    'circle-x': CircleX,
    close: X,
    code: Code,
    copy: Copy,
    crop: Crop,
    database: Database,
    delete: Trash2,
    download: Download,
    edit: Pencil,
    eraser: Eraser,
    expand: Expand,
    'external-link': ExternalLink,
    eye: Eye,
    'eye-off': EyeOff,
    file: File,
    'file-audio': FileAudio,
    'file-braces': FileBraces,
    'file-image': FileImage,
    'file-spreadsheet': FileSpreadsheet,
    'file-text': FileText,
    'file-up': FileUp,
    folder: Folder,
    'folder-plus': FolderPlus,
    hand: Hand,
    'heading-1': Heading1,
    'heading-2': Heading2,
    'heading-3': Heading3,
    italic: Italic,
    languages: Languages,
    link: Link,
    list: List,
    'list-ordered': ListOrdered,
    loader: LoaderCircle,
    'map-pin': MapPin,
    'map-pin-pen': MapPinPen,
    'message-circle': MessageCircle,
    'message-circle-plus': MessageCirclePlus,
    mic: Mic,
    moon: Moon,
    'panel-left': PanelLeft,
    'panel-left-close': PanelLeftClose,
    pause: Pause,
    play: Play,
    rectangle: Square,
    redo: Redo2,
    refresh: RefreshCw,
    'rotate-ccw': RotateCcw,
    'rotate-cw': RotateCw,
    'rotate-fine-ccw': RotateFineCcw,
    'rotate-fine-cw': RotateFineCw,
    save: Save,
    search: Search,
    'search-x': SearchX,
    send: Send,
    settings: Settings,
    'skip-back': SkipBack,
    'skip-forward': SkipForward,
    'text-quote': TextQuote,
    'triangle-alert': TriangleAlert,
    underline: Underline,
    undo: Undo2,
    unlink: Unlink,
    volume: Volume2,
    wrench: Wrench,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
  }

  let { name, size = 16 }: { name: ActionIconName; size?: ActionIconSize } = $props()

  const Icon = $derived(ICONS[name])
</script>

<!--
  aria-hidden is not passed here: Lucide adds it to every icon that has no
  children and no a11y prop of its own, and the in-house icons under ./icons
  hardcode it. ActionIcon.test.ts asserts it holds across the whole catalogue,
  so the guarantee is checked rather than repeated.
-->
<Icon {size} />
