//! Test-only helpers for the sync module (DESIGN §13.3). Builds an in-memory DB
//! that carries the REAL application schema (exported from the JS migration
//! registry into `tests/fixtures/schema_full.sql`), then layers the sync schema
//! on top. The module is gated with `#[cfg(test)]` at its declaration in
//! `sync/mod.rs`, so it never ships in the binary.

use rusqlite::Connection;

use crate::sync::schema::ensure_sync_schema;

/// The checked-in schema fixture: the concatenation of every JS migration's SQL
/// plus the programmatic layouts DDL. Generated by
/// `packages/store/scripts/export-schema.mjs`; a vitest test asserts it stays in
/// sync with the registry.
pub const SCHEMA_FIXTURE: &str = include_str!("../../tests/fixtures/schema_full.sql");

/// Opens an in-memory DB configured like a real sync connection and loads the
/// full application schema fixture. Does NOT install sync triggers — call
/// [`crate::sync::capture::ensure_capture`] for that.
pub fn new_app_schema_db() -> Connection {
    let conn = Connection::open_in_memory().expect("open in-memory db");
    conn.execute_batch(
        "PRAGMA journal_mode=MEMORY; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;",
    )
    .expect("configure pragmas");
    conn.execute_batch(SCHEMA_FIXTURE)
        .expect("apply schema fixture");
    conn
}

/// Like [`new_app_schema_db`] but also ensures the sync schema is present, ready
/// for capture/trigger tests.
pub fn new_synced_test_db() -> Connection {
    let conn = new_app_schema_db();
    ensure_sync_schema(&conn).expect("ensure sync schema");
    conn
}

fn meta_set(conn: &Connection, key: &str, value: &str) {
    conn.execute(
        "INSERT INTO sync_meta(key, value) VALUES (?1, ?2)
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        rusqlite::params![key, value],
    )
    .expect("write sync_meta");
}

/// Marks a sync session as configured (sets `device_id`) without enabling
/// capture — mirrors the post-login, pre-`capture_enabled` window.
pub fn set_session(conn: &Connection) {
    meta_set(conn, "device_id", "test-device");
}

/// Configures a session AND enables capture (`device_id` + `capture_enabled=1`).
pub fn set_session_with_capture(conn: &Connection) {
    set_session(conn);
    meta_set(conn, "capture_enabled", "1");
}

/// Total rows in `sync_oplog`.
pub fn oplog_count(conn: &Connection) -> i64 {
    conn.query_row("SELECT COUNT(*) FROM sync_oplog", [], |row| row.get(0))
        .expect("count oplog")
}

/// Rows in `sync_oplog` for a given table.
pub fn oplog_count_for(conn: &Connection, table: &str) -> i64 {
    conn.query_row(
        "SELECT COUNT(*) FROM sync_oplog WHERE table_name = ?1",
        [table],
        |row| row.get(0),
    )
    .expect("count oplog for table")
}

/// Number of installed `trg_sync_*` triggers.
pub fn trg_sync_count(conn: &Connection) -> i64 {
    conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name LIKE 'trg_sync_%'",
        [],
        |row| row.get(0),
    )
    .expect("count sync triggers")
}

// ---------------------------------------------------------------------------
// MockSyncApi — in-memory [`SyncApi`] for push/blob tests (no server needed).
// ---------------------------------------------------------------------------

use crate::sync::http::{
    BlobExists, DeleteAccountRequest, DevicesResponse, HealthResponse, LoginRequest, LoginResponse,
    NotificationItem, PlanCatalogItem, PlanChangeRequestResponse, PullResponse, PushChange,
    PushRequest, PushResponse, PushResult, RegisterRequest, RegisterResponse, SyncApi, SyncError,
    UsageResponse,
};
use std::sync::Mutex;

/// Configurable in-memory [`SyncApi`] double. Records pushed changes and returns
/// canned per-row results. Optionally rejects any push batch larger than
/// `max_batch_changes` with a `413 payload_too_large` so the bisection path can
/// be exercised. Blob HEADs return whatever is in `existing_blobs`.
pub struct MockSyncApi {
    /// All changes the mock received across every (sub)batch, in order.
    pub pushed: Mutex<Vec<PushChange>>,
    /// SHAs the server already has (HEAD → 200).
    pub existing_blobs: Mutex<std::collections::HashSet<String>>,
    /// SHAs that were PUT during the test.
    pub put_blobs: Mutex<Vec<String>>,
    /// When `Some(n)`, any batch with more than `n` changes is rejected 413.
    pub max_batch_changes: Option<usize>,
    /// Status assigned to every result row ("applied" by default).
    pub result_status: String,
    /// Monotonic server_seq assigned to results.
    next_seq: Mutex<i64>,
    pub server_now_ms: i64,
    pub server_epoch: String,
    /// Canned pull pages served in order on each `pull` call (queue popped from
    /// the front). When empty, `pull` returns an empty terminal page.
    pub pull_pages: Mutex<std::collections::VecDeque<PullResponse>>,
    /// Bytes the server serves for `blob_get`, keyed by sha256. A missing key
    /// produces a `404`.
    pub blob_bytes: Mutex<std::collections::HashMap<String, Vec<u8>>>,
    /// When `Some(n)`, the first `n` `pull` calls return `409 cursor_ahead`
    /// before serving normally (drives the reconciliation path). Decrements.
    pub cursor_ahead_remaining: Mutex<i64>,
    /// Canned plan catalog served by `list_plans`.
    pub plans: Mutex<Vec<PlanCatalogItem>>,
    /// Canned notification inbox served by `list_notifications`.
    pub notifications: Mutex<Vec<NotificationItem>>,
    /// When `true`, `request_plan_change` returns `409 plan_request_pending`.
    pub plan_request_pending: Mutex<bool>,
    /// Records the `(requested_plan_id, note)` of the last `request_plan_change`.
    pub plan_change_calls: Mutex<Vec<(String, Option<String>)>>,
    /// Records the ids passed to `mark_notification_read`, in order.
    pub marked_read: Mutex<Vec<String>>,
    /// Canned usage snapshot served by `usage` (lets tests assert the extended fields).
    pub usage: Mutex<UsageResponse>,
}

impl Default for MockSyncApi {
    fn default() -> Self {
        Self {
            pushed: Mutex::new(Vec::new()),
            existing_blobs: Mutex::new(std::collections::HashSet::new()),
            put_blobs: Mutex::new(Vec::new()),
            max_batch_changes: None,
            result_status: "applied".to_string(),
            next_seq: Mutex::new(1),
            server_now_ms: 1_700_000_000_000,
            server_epoch: "mock-epoch".to_string(),
            pull_pages: Mutex::new(std::collections::VecDeque::new()),
            blob_bytes: Mutex::new(std::collections::HashMap::new()),
            cursor_ahead_remaining: Mutex::new(0),
            plans: Mutex::new(Vec::new()),
            notifications: Mutex::new(Vec::new()),
            plan_request_pending: Mutex::new(false),
            plan_change_calls: Mutex::new(Vec::new()),
            marked_read: Mutex::new(Vec::new()),
            usage: Mutex::new(UsageResponse {
                rows: 0,
                blobs_count: 0,
                blobs_bytes: 0,
                quota_bytes: 0,
                plan_name: None,
                expires_at: None,
                unread_notifications: 0,
                pending_plan_request: None,
            }),
        }
    }
}

impl MockSyncApi {
    pub fn with_max_batch(max: usize) -> Self {
        Self {
            max_batch_changes: Some(max),
            ..Default::default()
        }
    }

    /// Total number of changes recorded across all (sub)batches.
    pub fn pushed_count(&self) -> usize {
        self.pushed.lock().unwrap().len()
    }

    /// Queues a canned pull page (served FIFO on subsequent `pull` calls).
    pub fn queue_pull_page(&self, page: PullResponse) {
        self.pull_pages.lock().unwrap().push_back(page);
    }

    /// Stores blob bytes the server will serve for `blob_get`.
    pub fn put_blob_bytes(&self, sha256: &str, bytes: Vec<u8>) {
        self.blob_bytes
            .lock()
            .unwrap()
            .insert(sha256.to_string(), bytes);
    }

    /// Makes the next `n` `pull` calls return `409 cursor_ahead`.
    pub fn set_cursor_ahead(&self, n: i64) {
        *self.cursor_ahead_remaining.lock().unwrap() = n;
    }
}

impl SyncApi for MockSyncApi {
    async fn register(&self, _req: RegisterRequest) -> Result<RegisterResponse, SyncError> {
        Ok(RegisterResponse {
            account_id: "mock-account".to_string(),
        })
    }

    async fn login(&self, _req: LoginRequest) -> Result<LoginResponse, SyncError> {
        Ok(LoginResponse {
            account_id: "mock-account".to_string(),
            device_id: "mock-device".to_string(),
            device_token: "mock-token".to_string(),
        })
    }

    async fn logout(&self, _token: &str) -> Result<(), SyncError> {
        Ok(())
    }

    async fn devices(&self, _token: &str) -> Result<DevicesResponse, SyncError> {
        Ok(DevicesResponse {
            devices: Vec::new(),
        })
    }

    async fn revoke(&self, _token: &str, _device_id: &str) -> Result<(), SyncError> {
        Ok(())
    }

    async fn delete_account(
        &self,
        _token: &str,
        _req: DeleteAccountRequest,
    ) -> Result<(), SyncError> {
        Ok(())
    }

    async fn usage(&self, _token: &str) -> Result<UsageResponse, SyncError> {
        let u = self.usage.lock().unwrap();
        Ok(UsageResponse {
            rows: u.rows,
            blobs_count: u.blobs_count,
            blobs_bytes: u.blobs_bytes,
            quota_bytes: u.quota_bytes,
            plan_name: u.plan_name.clone(),
            expires_at: u.expires_at,
            unread_notifications: u.unread_notifications,
            pending_plan_request: u.pending_plan_request.clone(),
        })
    }

    async fn list_plans(&self, _token: &str) -> Result<Vec<PlanCatalogItem>, SyncError> {
        Ok(self.plans.lock().unwrap().clone())
    }

    async fn request_plan_change(
        &self,
        _token: &str,
        requested_plan_id: &str,
        note: Option<&str>,
    ) -> Result<PlanChangeRequestResponse, SyncError> {
        self.plan_change_calls
            .lock()
            .unwrap()
            .push((requested_plan_id.to_string(), note.map(str::to_string)));
        if *self.plan_request_pending.lock().unwrap() {
            return Err(SyncError::Api {
                status: 409,
                code: "plan_request_pending".to_string(),
                message: "ya hay una solicitud pendiente".to_string(),
            });
        }
        Ok(PlanChangeRequestResponse {
            id: "mock-request".to_string(),
            current_plan_id: None,
            requested_plan_id: requested_plan_id.to_string(),
            note: note.map(str::to_string),
            status: "pending".to_string(),
            created_at: self.server_now_ms,
        })
    }

    async fn list_notifications(
        &self,
        _token: &str,
        _since: Option<&str>,
        _limit: Option<i64>,
    ) -> Result<Vec<NotificationItem>, SyncError> {
        Ok(self.notifications.lock().unwrap().clone())
    }

    async fn mark_notification_read(&self, _token: &str, id: &str) -> Result<(), SyncError> {
        self.marked_read.lock().unwrap().push(id.to_string());
        Ok(())
    }

    async fn health(&self) -> Result<HealthResponse, SyncError> {
        Ok(HealthResponse {
            status: "ok".to_string(),
            version: "test".to_string(),
            epoch: self.server_epoch.clone(),
            server_now_ms: self.server_now_ms,
            limits: Default::default(),
        })
    }

    async fn push(
        &self,
        _token: &str,
        _schema_tag: &str,
        req: PushRequest,
    ) -> Result<PushResponse, SyncError> {
        if let Some(max) = self.max_batch_changes {
            if req.changes.len() > max {
                return Err(SyncError::Api {
                    status: 413,
                    code: "payload_too_large".to_string(),
                    message: "batch too large".to_string(),
                });
            }
        }

        let mut results = Vec::with_capacity(req.changes.len());
        {
            let mut seq = self.next_seq.lock().unwrap();
            for change in &req.changes {
                let server_seq = *seq;
                *seq += 1;
                results.push(PushResult {
                    table: change.table.clone(),
                    row_id: change.row_id.clone(),
                    status: self.result_status.clone(),
                    server_seq,
                    winner: None,
                });
            }
        }
        self.pushed.lock().unwrap().extend(req.changes);

        Ok(PushResponse {
            results,
            max_server_seq: *self.next_seq.lock().unwrap() - 1,
            server_epoch: self.server_epoch.clone(),
            server_now_ms: self.server_now_ms,
        })
    }

    async fn pull(
        &self,
        _token: &str,
        _schema_tag: &str,
        since: i64,
        _limit: i64,
    ) -> Result<PullResponse, SyncError> {
        // Optionally emit cursor_ahead first (reconciliation path).
        {
            let mut remaining = self.cursor_ahead_remaining.lock().unwrap();
            if *remaining > 0 {
                *remaining -= 1;
                return Err(SyncError::Api {
                    status: 409,
                    code: "cursor_ahead".to_string(),
                    message: "cursor ahead".to_string(),
                });
            }
        }
        // Serve a canned page if one is queued, else a terminal empty page.
        if let Some(page) = self.pull_pages.lock().unwrap().pop_front() {
            return Ok(page);
        }
        Ok(PullResponse {
            rows: Vec::new(),
            next_since: since,
            has_more: false,
            schema_tag: String::new(),
            server_epoch: self.server_epoch.clone(),
            server_now_ms: self.server_now_ms,
        })
    }

    async fn blob_head(&self, _token: &str, sha256: &str) -> Result<BlobExists, SyncError> {
        Ok(self.existing_blobs.lock().unwrap().contains(sha256))
    }

    async fn blob_put(&self, _token: &str, sha256: &str, _bytes: Vec<u8>) -> Result<(), SyncError> {
        self.put_blobs.lock().unwrap().push(sha256.to_string());
        self.existing_blobs
            .lock()
            .unwrap()
            .insert(sha256.to_string());
        Ok(())
    }

    async fn blob_get(&self, _token: &str, sha256: &str) -> Result<reqwest::Response, SyncError> {
        let bytes = self.blob_bytes.lock().unwrap().get(sha256).cloned();
        match bytes {
            Some(bytes) => {
                // Build a 200 reqwest::Response from raw bytes via http::Response.
                let http_resp = http::Response::builder()
                    .status(200)
                    .body(bytes)
                    .map_err(|e| SyncError::Network(format!("mock response build: {e}")))?;
                Ok(reqwest::Response::from(http_resp))
            }
            None => Err(SyncError::Api {
                status: 404,
                code: "not_found".to_string(),
                message: "blob not found".to_string(),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn plan(id: &str, name: &str, is_current: bool) -> PlanCatalogItem {
        PlanCatalogItem {
            id: id.to_string(),
            name: name.to_string(),
            quota_bytes: 0,
            price_cents: 0,
            currency: "USD".to_string(),
            period: "none".to_string(),
            description: None,
            is_current,
        }
    }

    fn notif(id: &str, kind: &str) -> NotificationItem {
        NotificationItem {
            id: id.to_string(),
            kind: kind.to_string(),
            category: String::new(),
            severity: "info".to_string(),
            title: "T".to_string(),
            body: "B".to_string(),
            created_at: 1,
            read_at: None,
        }
    }

    #[tokio::test]
    async fn list_plans_returns_canned_catalog() {
        let api = MockSyncApi::default();
        *api.plans.lock().unwrap() = vec![plan("p0", "Free", true), plan("p1", "5 GB", false)];
        let plans = api.list_plans("tok").await.expect("plans");
        assert_eq!(plans.len(), 2);
        assert!(plans[0].is_current);
        assert_eq!(plans[1].name, "5 GB");
    }

    #[tokio::test]
    async fn request_plan_change_returns_pending_request_and_records_call() {
        let api = MockSyncApi::default();
        let resp = api
            .request_plan_change("tok", "p2", Some("más espacio"))
            .await
            .expect("plan change");
        assert_eq!(resp.requested_plan_id, "p2");
        assert_eq!(resp.status, "pending");
        assert_eq!(resp.note.as_deref(), Some("más espacio"));
        let calls = api.plan_change_calls.lock().unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].0, "p2");
    }

    #[tokio::test]
    async fn request_plan_change_maps_409_to_pending_api_error() {
        let api = MockSyncApi::default();
        *api.plan_request_pending.lock().unwrap() = true;
        let err = api
            .request_plan_change("tok", "p2", None)
            .await
            .expect_err("must conflict");
        assert_eq!(err.status(), Some(409));
        assert_eq!(err.api_code(), Some("plan_request_pending"));
    }

    #[tokio::test]
    async fn list_notifications_returns_canned_inbox() {
        let api = MockSyncApi::default();
        *api.notifications.lock().unwrap() = vec![
            notif("n1", "subscription_reminder"),
            notif("n2", "request_approved"),
        ];
        let inbox = api
            .list_notifications("tok", None, Some(50))
            .await
            .expect("inbox");
        assert_eq!(inbox.len(), 2);
        assert_eq!(inbox[0].kind, "subscription_reminder");
    }

    #[tokio::test]
    async fn mark_notification_read_records_id() {
        let api = MockSyncApi::default();
        api.mark_notification_read("tok", "n1").await.expect("mark");
        assert_eq!(
            api.marked_read.lock().unwrap().as_slice(),
            &["n1".to_string()]
        );
    }

    #[tokio::test]
    async fn usage_returns_extended_canned_snapshot() {
        let api = MockSyncApi::default();
        *api.usage.lock().unwrap() = UsageResponse {
            rows: 1,
            blobs_count: 2,
            blobs_bytes: 3,
            quota_bytes: 100,
            plan_name: Some("10 GB".to_string()),
            expires_at: Some(1760000000000),
            unread_notifications: 4,
            pending_plan_request: Some("50 GB".to_string()),
        };
        let usage = api.usage("tok").await.expect("usage");
        assert_eq!(usage.unread_notifications, 4);
        assert_eq!(usage.expires_at, Some(1760000000000));
        assert_eq!(usage.pending_plan_request.as_deref(), Some("50 GB"));
    }

    #[test]
    fn fixture_creates_all_synced_base_tables() {
        let conn = new_app_schema_db();
        for table in crate::sync::capture::SYNCED_TABLES {
            let exists: bool = conn
                .query_row(
                    "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?1",
                    [table],
                    |_| Ok(true),
                )
                .unwrap_or(false);
            assert!(exists, "fixture is missing synced table {table}");
        }
    }

    #[test]
    fn fixture_includes_generated_search_text_and_fts() {
        let conn = new_app_schema_db();
        // items.search_text is a GENERATED column (DESIGN §2) — inserting without
        // it must succeed and the column must be present + hidden in table_xinfo.
        conn.execute(
            "INSERT INTO items(id,title,collection_id,created_at,updated_at)
             SELECT 'i1','T', c.id, 1, 1 FROM (SELECT 'c1' AS id) c
             WHERE 1=1",
            [],
        )
        .ok();
        let fts_exists: bool = conn
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE name='fts_items'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        assert!(
            fts_exists,
            "fixture should create the fts_items virtual table"
        );
    }
}
